# Generated by Django 3.1.1 on 2020-09-18 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_working', models.DateTimeField(default=None)),
                ('end_working', models.DateTimeField(default=None)),
                ('users_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workingtime', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-start_working',),
            },
        ),
    ]
