# Generated by Django 3.1.1 on 2020-09-18 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workingtime', '0002_auto_20200918_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingtime',
            name='users_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workingtime', to=settings.AUTH_USER_MODEL),
        ),
    ]
