# Generated by Django 3.1.1 on 2020-09-18 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
        ('workingtime', '0003_auto_20200918_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingtime',
            name='users_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workingtime', to='userprofile.userprofile'),
        ),
    ]
