# Generated by Django 3.1.1 on 2020-09-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workingtime', '0004_auto_20200918_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingtime',
            name='at_work',
            field=models.BooleanField(default=False),
        ),
    ]
