# Generated by Django 3.1.1 on 2020-09-28 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workingtime', '0005_workingtime_at_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workingtime',
            name='at_work',
        ),
    ]
