# Generated by Django 3.1.1 on 2020-09-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workingtime', '0006_remove_workingtime_at_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingtime',
            name='worked_time',
            field=models.DateTimeField(default=None),
        ),
    ]
