# Generated by Django 3.1.1 on 2020-09-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workingtime', '0008_auto_20200929_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingtime',
            name='worked_time',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
