# Generated by Django 3.1.1 on 2020-10-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workingtime', '0010_auto_20200929_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingtime',
            name='end_working',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='workingtime',
            name='start_working',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
