# Generated by Django 3.1.1 on 2020-10-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workingtime', '0011_auto_20201001_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingtime',
            name='done_working',
            field=models.BooleanField(default=False),
        ),
    ]
