# Generated by Django 3.1.1 on 2020-10-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workingtime', '0012_workingtime_done_working'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingtime',
            name='done_working',
            field=models.BooleanField(default=True),
        ),
    ]
