# Generated by Django 3.1.1 on 2020-10-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workingtime', '0017_auto_20201009_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingtime',
            name='is_approved_by_supervisor',
            field=models.BooleanField(default=False),
        ),
    ]
