# Generated by Django 3.1.1 on 2020-10-10 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workingtime', '0019_workingtime_for_employee_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workingtime',
            name='for_employee_info',
        ),
    ]
