# Generated by Django 3.1.1 on 2020-10-12 17:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workingtime', '0022_auto_20201012_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingtime',
            name='end_working_corrected',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='workingtime',
            name='start_working_corrected',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
