# Generated by Django 3.1.1 on 2020-10-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workingtime', '0023_auto_20201012_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingtime',
            name='worked_time_corrected',
            field=models.CharField(default='', max_length=255),
        ),
    ]
