# Generated by Django 3.1.1 on 2020-10-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workingtime', '0024_workingtime_worked_time_corrected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingtime',
            name='end_working',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='workingtime',
            name='start_working',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
