# Generated by Django 3.1.1 on 2020-10-13 11:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workingtime', '0025_auto_20201012_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingtime',
            name='end_working',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='workingtime',
            name='start_working',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
