# Generated by Django 3.1.1 on 2020-10-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workingtime', '0026_auto_20201013_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingtime',
            name='start_working',
            field=models.DateTimeField(default='2020-10-13 11:34:54'),
        ),
    ]
