# Generated by Django 3.1.1 on 2020-10-13 11:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workingtime', '0028_auto_20201013_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingtime',
            name='start_working_time',
            field=models.TimeField(default='11:48:45'),
        ),
        migrations.AlterField(
            model_name='workingtime',
            name='start_working',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='workingtime',
            name='start_working_date',
            field=models.DateField(default='2020-10-13'),
        ),
    ]
