# Generated by Django 3.1.1 on 2020-10-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workingtime', '0028_auto_20201013_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workingtime',
            options={},
        ),
        migrations.RemoveField(
            model_name='workingtime',
            name='start_working',
        ),
        migrations.RemoveField(
            model_name='workingtime',
            name='start_working_date',
        ),
        migrations.AddField(
            model_name='workingtime',
            name='corrected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workingtime',
            name='corrected_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workingtime',
            name='worked_time_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workingtime',
            name='end_working',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='workingtime',
            name='end_working_corrected',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='workingtime',
            name='worked_time',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workingtime',
            name='worked_time_corrected',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
