# Generated by Django 3.1.1 on 2020-10-20 15:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workingtime', '0029_auto_20201020_1746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workingtime',
            options={'ordering': ('-start_working',)},
        ),
        migrations.AddField(
            model_name='workingtime',
            name='start_working',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
