# Generated by Django 3.1.1 on 2020-10-13 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workingtime', '0029_auto_20201013_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workingtime',
            name='start_working_date',
        ),
        migrations.RemoveField(
            model_name='workingtime',
            name='start_working_time',
        ),
    ]
