# Generated by Django 3.1.1 on 2020-10-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workingtime', '0030_auto_20201020_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingtime',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
