# Generated by Django 3.1.1 on 2020-10-15 08:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workingtime', '0030_auto_20201013_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingtime',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='workingtime',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
