# Generated by Django 3.1.1 on 2020-10-16 17:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workingtime', '0031_auto_20201015_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingtime',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='workingtime',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
