# Generated by Django 3.1.1 on 2020-10-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workingtime', '0033_auto_20201018_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingtime',
            name='corrected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workingtime',
            name='corrected_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workingtime',
            name='worked_time_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
