# Generated by Django 3.1.1 on 2020-10-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workingtime', '0034_auto_20201018_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingtime',
            name='worked_time',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workingtime',
            name='worked_time_corrected',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
