# Generated by Django 3.1.1 on 2020-10-19 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workingtime', '0036_auto_20201019_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workingtime',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='workingtime',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='workingtime',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='workingtime',
            name='start_time',
        ),
    ]
