# Generated by Django 3.1.1 on 2020-10-22 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workingtime', '0032_auto_20201022_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingChangeLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.CharField(default='', max_length=50)),
                ('time_end', models.CharField(default='', max_length=50)),
                ('notes', models.CharField(default='', max_length=100)),
                ('changed_by', models.CharField(default='', max_length=60)),
                ('changed_at', models.CharField(default='', max_length=50)),
                ('workingtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workinglogs', to='workingtime.workingtime')),
            ],
        ),
    ]
