# Generated by Django 3.1.1 on 2020-10-21 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workingtime', '0031_workingtime_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingChangeLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_changes', models.CharField(max_length=200)),
                ('workingtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workinglogs', to='workingtime.workingtime')),
            ],
        ),
    ]
