# Generated by Django 3.1.1 on 2020-10-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_auto_20201022_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingchangelogs',
            name='changed_at',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='workingchangelogs',
            name='time_end',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workingchangelogs',
            name='time_start',
            field=models.CharField(max_length=50),
        ),
    ]
