# Generated by Django 3.1.1 on 2020-09-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20200928_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='at_work',
            field=models.BooleanField(default=False),
        ),
    ]
