# Generated by Django 3.1.1 on 2020-10-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_userprofile_at_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='worked_today',
            field=models.BooleanField(default=False),
        ),
    ]
