# Generated by Django 3.1.1 on 2020-10-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0010_auto_20201008_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='confirmed_employee',
            field=models.BooleanField(default=False),
        ),
    ]
