# Generated by Django 3.1.1 on 2020-10-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0013_auto_20201009_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(choices=[('Unspecify', 'Unspecify'), ('Restaurant - BFST', 'Restaurant - BFST'), ('Restaurant - Evening', 'Restaurant - Evening'), ('RoomService - Morning', 'RoomService - Morning'), ('RoomService - Evening', 'RoomService - Evening'), ('Banket - Morning', 'Banket - Morning'), ('Banket - Evening', 'Banket - Evening')], default='unknown', max_length=100),
        ),
    ]
