# Generated by Django 3.1.1 on 2020-10-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0014_auto_20201009_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='supervisor',
            field=models.BooleanField(default=False),
        ),
    ]
