# Generated by Django 3.1.1 on 2020-10-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0017_userprofile_fully_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='checked_account',
            field=models.BooleanField(default=False),
        ),
    ]
