# Generated by Django 3.1.1 on 2020-10-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0018_userprofile_checked_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='manager',
            field=models.BooleanField(default=False),
        ),
    ]
