# Generated by Django 3.1.1 on 2020-10-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0019_userprofile_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(choices=[('Unspecify', 'Unspecify'), ('F&B Manager', 'F&B Manager'), ('Restaurant - BFST', 'Restaurant - BFST'), ('Restaurant - Evening', 'Restaurant - Evening'), ('RoomService - Morning', 'RoomService - Morning'), ('RoomService - Evening', 'RoomService - Evening'), ('Banket - Morning', 'Banket - Morning'), ('Banket - Evening', 'Banket - Evening')], default='Unspecify', max_length=100),
        ),
    ]
